spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/data_pipeline
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB      
      max-request-size: 50MB
      enabled: true         

# 애플리케이션 설정
app:
  file:
    max-size: 10485760  # 10MB in bytes
    upload-dir: ./uploads  # 파일 저장 경로

# Logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.core.data_pipeline_platform: DEBUG